ARG RUBY_VERSION=3.3.5-alpine
FROM ruby:$RUBY_VERSION

RUN apk add --no-cache --update build-base \
  bash \
  git \
  postgresql-dev \
  postgresql-client \
  nodejs \
  yarn \
  gcompat \
  imagemagick \
  vips \
  tzdata \
  wget \
  && rm -rf /var/cache/apk/*

RUN mkdir -p /app

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN gem update --system
RUN bundle install -j $(nproc)