x-base: &base
  build:
    context: .
    dockerfile: ./Dockerfile.dev
    args:
      RUBY_VERSION: '3.3.5-alpine'
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle
  environment:
    - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    - RAILS_ENV=development
    - POSTGRES_HOST=postgres
    - POSTGRES_DB=dwh_base_development
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  depends_on:
    - postgres

services:
  app:
    <<: *base
    command: bash -c 'rm -f tmp/pids/server.pid && bundle install && foreman start -f Procfile.dev'
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    
  postgres:
    image: postgres:16
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  good_job:
    <<: *base
    command: bash -c 'bundle exec good_job start'

volumes:
  bundle:
  postgres:  