x-base: &base
  build:
    context: .
    dockerfile: ./Dockerfile.dev
    args:
      RUBY_VERSION: '3.3.5-alpine'
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
  environment:
    - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    - RAILS_ENV=development
    - POSTGRES_HOST=postgres
    - POSTGRES_DB=saas_kickstarter_development
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  depends_on:
    - postgres

services:
  app:
    <<: *base
    command: bash -c 'rm -f tmp/pids/server.pid && bundle install && bin/rails server -p 3000 -b 0.0.0.0'
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres

  css:
    <<: *base
    command: yarn build:css --watch

  js:
    <<: *base
    command: yarn build --watch

  postgres:
    image: postgres:16
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  bundle:
  node_modules:
  postgres: