x-base: &base
  build:
    context: .
    dockerfile: ./Dockerfile.dev
    args:
      RUBY_VERSION: '3.3.5-alpine'
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle
  environment:
    - DATABASE_URL=postgres://postgres:postgres@db:5432
    - RAILS_ENV=development
    - POSTGRES_HOST=db
    - POSTGRES_DB=dwh_development
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  depends_on:
    - db

services:
  app:
    <<: *base
    command: bash -c '
      rm -f tmp/pids/server.pid && 
      bundle install && 
      gem install foreman && 
      bundle exec rails db:create && 
      bundle exec rails db:migrate && 
      foreman start -f Procfile.dev'
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    environment:
      OLLAMA_URL: http://ollama:11434

  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

volumes:
  bundle:
  postgres_data: