default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    host: db
    database: dwh_base_development
    username: postgres
    password: postgres
  dwh:
    <<: *default
    host: db
    database: dwh_data_development
    username: postgres
    password: postgres
    migrations_paths: ["db/dwh_migrate"]

test:
  primary:
    <<: *default
    host: db
    database: dwh_base_test
    username: postgres
    password: postgres
  dwh:
    <<: *default
    host: db
    database: dwh_data_test
    username: postgres
    password: postgres
    migrations_paths: ["db/dwh_migrate"]

production:
  primary:
    <<: *default
    host: <%= ENV["POSTGRESQL_HOST"] %>
    database: <%= ENV["POSTGRESQL_DATABASE"] %>
    username: <%= ENV["POSTGRESQL_USERNAME"] %>
    password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  dwh:
    <<: *default
    host: <%= ENV["POSTGRESQL_DWH_HOST"] %>
    database: <%= ENV["POSTGRESQL_DWH_DATABASE"] %>
    username: <%= ENV["POSTGRESQL_DWH_USERNAME"] %>
    password: <%= ENV["POSTGRESQL_DWH_PASSWORD"] %>
    migrations_paths: ["db/dwh_migrate"]